### PR TITLE
Support for latest Ractive 0.9.4 cssData / css templating

### PR DESCRIPTION
**Pull request by avoto**

### CODE REVIEW

**Comment by fskreuz** [comment]
Was looking into this when I noticed that it's introducing `dist` into the repo when it shouldn't. Any reason why this is the case?

**Comment by fskreuz** [comment]
Looks like `dist` is only there for npm publishing, it shouldn't be in the repo. Feel free to amend commits/force-push to this PR's branch. I have not merged it to master just yet.

**Comment by anatolipr** [comment]
@fskreuz - ah, yeah I got rid of it, sorry it was wrongly committed. :)

**Comment by anatolipr** [comment]
Actually, I just noticed a test that I need to fix before this gets into master.

**Comment by fskreuz** [comment]
Changes merged in the other PR. Thanks for your contributions! 👍

**Pull request closed without merging**
