### PR TITLE
Update Ractive dependency to ^0.8.0 & rcu version

### PR DESCRIPTION
**Pull request by mpowell-atomic**
Hi. Should this be updated now 0.8.x is out? Thanks!

### CODE REVIEW

**Comment by fskreuz** [comment]
Haven't been using rcu in quite a while, but this looks good to me.

**Comment by pidgpowell** [comment]
cheers. it is used by the ractive-component-loader for webpack so that's my main concern. i forked ractive-component-loader while 0.8 was in edge but with a glorious new release of ractive it'd be nice to not have to do that.

**Comment by fskreuz** [comment]
I think I'll just merge this one to lock rcu to 0.8. Tests say pass. Here goes... 💣

**Comment by pidgpowell** [comment]
Guess we just need a new tag now for 0.9.0? Argh. Just realized I posted from a different github account... Sigh.

**Comment by Rich-Harris** [comment]
@pidgpowell / @mpowell-atomic – I've just published `rcu@0.9.0` to npm. thanks 👍

**Comment by mpowell-atomic** [comment]
@Rich-Harris thank you!

**Pull request merged**
