### PR TITLE
remove tippex dependency

### PR DESCRIPTION
**Pull request by heavyk**
hi @Rich-Harris 
I had some problems with the tippex dependency after I upgradied rcu. I found it easy to just use string replacement to replace comments with whitespace. all tests pass and commented out requires are not included (which was where I began in the first place)

cheers

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Can you elaborate? Remove comments with `string.replace` definitely isn't robust – e.g. if you have something like 

```js
var str = '/* this looks like a comment */';
var otherStr = 'this looks like a require("statement")';
```

If there's a problem with tippex, we should fix the problem with tippex

**Comment by heavyk** [comment]
sure, I would got undefined function `match` and I didn't have time to go debugging.

I wrote this code two nights ago. let me see if I can figure out if I have all the cases

**Comment by heavyk** [comment]
you are correct. I forsee a bug in my code, where I could have:

```js
var s = "string me this /*;
console.log(s. '*/')
```

actually to solve it in our code, I originally started out with something a bit better: I used babel-core and then walk the ast for comments replacing with whitespace then pretty print back out.

that method could fuck up whitesace though ... I didn't look into ensuring babel will definitely have the same number of newlines on output though. because I'm sure we don't have that edge case in our code, turns out this was short and easy and this simple replace didn't fuck up the source maps 

I'm willing to improve this PR. what would be best?

**Comment by Rich-Harris** [comment]
Using Babel is a non-starter – it's a really big and slow dependency for something that potentially needs to run in a browser. You still haven't told me what the problem with tippex is!

**Comment by heavyk** [comment]
it was trying to call a function called `match` which was undefined. let me see if I can recreate the error

**Comment by Rich-Harris** [comment]
Ah sorry, you said that in a comment I missed. Could be an out of date version – try reinstalling?

**Comment by heavyk** [comment]
so I'm trying to recreate the error here and I'm not getting it. I don't understand...

I think I know the problem: it's 2:45 here, so I think should call it a night. I'll go back to you in the morning with a clear head. maybe itt is working now all of a sudden. I hope so!

good night

**Comment by heavyk** [comment]
oh my, my memory was wrong: the function is called `state` not `match`

here's the exact error using rcu@0.6.2

```
input:  /Users/kenny/Projects/affinaty/affinaty-ractive/src
output: /Users/kenny/Projects/affinaty/affinaty-ractive/.gobble/01-ractive/4
>>>
===
/Users/kenny/Projects/affinaty/affinaty-ractive/src/partials/debate-stats.html
===
state is not a function
TypeError: state is not a function
    at find (/Users/kenny/Projects/affinaty/affinaty-ractive/node_modules/rcu/dist/rcu.umd.js:463:13)
    at match (/Users/kenny/Projects/affinaty/affinaty-ractive/node_modules/rcu/dist/rcu.umd.js:472:16)
    at Object.parse (/Users/kenny/Projects/affinaty/affinaty-ractive/node_modules/rcu/dist/rcu.umd.js:621:5)
    at Object.ractive (/Users/kenny/Projects/affinaty/affinaty-ractive/gobble-ractive.js:22:19)
    at /Users/kenny/Projects/affinaty/affinaty-ractive/node_modules/gobble/dist/gobble.js:299:28
    at lib$es6$promise$$internal$$tryCatch (/Users/kenny/Projects/affinaty/affinaty-ractive/node_modules/es6-promise/dist/es6-promise.js:331:16)
    at lib$es6$promise$$internal$$invokeCallback (/Users/kenny/Projects/affinaty/affinaty-ractive/node_modules/es6-promise/dist/es6-promise.js:343:17)
    at lib$es6$promise$$internal$$publish (/Users/kenny/Projects/affinaty/affinaty-ractive/node_modules/es6-promise/dist/es6-promise.js:314:11)
    at lib$es6$promise$asap$$flush (/Users/kenny/Projects/affinaty/affinaty-ractive/node_modules/es6-promise/dist/es6-promise.js:125:9)
    at nextTickCallbackWith0Args (node.js:452:9)
<<<
```

would the file in question "src/partials/debate-stats.html" be helpful?

**Comment by Rich-Harris** [comment]
> would the file in question "src/partials/debate-stats.html" be helpful?

Yes, it would – it looks like Tippex is getting tripped up by some syntax. Would be useful to see the JavaScript in question.

**Comment by heavyk** [comment]
https://github.com/heavyk/affinaty/blob/develop/src/partials/debate-stats.html

**Comment by heavyk** [comment]
found it!

```js
for (gender = 0; gender < num_planets; gender++)
      percents[gender] = planets[gender] / total * 100

```

sorry for the nasty code :/

**Comment by heavyk** [comment]
seems it doesn't like not having the brackets.

now I have a different bug... investigating

**Comment by heavyk** [comment]
I have distilled this error down into a test case for you (save you some time) here: https://github.com/Rich-Harris/tippex/pull/2

there are actually two errors I've found.
------------

I still have another error related to this latest version of rcu which I'm investigating (it actually fails seemingly unrelated in the next derequire phase - yet with this PR applied it does not - so I don't know..) I'll open another issue when I find it.

cheers

**Pull request closed without merging**
